CREATE TABLE PROJECT (
  PROJECT_ID SERIAL NOT NULL  COMMENT 'プロジェクトID',
  PROJECT_NAME VARCHAR(128) NOT NULL  COMMENT 'プロジェクト名',
  PROJECT_TYPE VARCHAR(128) NOT NULL  COMMENT 'プロジェクト種別',
  PROJECT_CLASS VARCHAR(128) NOT NULL  COMMENT 'プロジェクト分類',
  PROJECT_START_DATE DATE NULL DEFAULT NULL  COMMENT 'プロジェクト開始日付',
  PROJECT_END_DATE DATE NULL DEFAULT NULL  COMMENT 'プロジェクト終了日付',
  CLIENT_ID INT NULL DEFAULT NULL  COMMENT '顧客ID',
  PROJECT_MANAGER VARCHAR(128) NULL DEFAULT NULL  COMMENT 'プロジェクトマネージャー',
  PROJECT_LEADER VARCHAR(128) NULL DEFAULT NULL  COMMENT 'プロジェクトリーダー',
  USER_ID INT NULL DEFAULT NULL  COMMENT 'ユーザID',
  NOTE VARCHAR(512) NULL DEFAULT NULL  COMMENT '備考',
  SALES INT NULL DEFAULT NULL  COMMENT '売上高',
  COST_OF_GOODS_SOLD INT NULL DEFAULT NULL  COMMENT '売上原価',
  SGA INT NULL DEFAULT NULL  COMMENT '販管費',
  ALLOCATION_OF_CORP_EXPENSES INT NULL DEFAULT NULL  COMMENT '本社配賦'
)
COMMENT='プロジェクト'