CREATE TABLE SYSTEM_ACCOUNT (
  USER_ID SERIAL NOT NULL  COMMENT 'ユーザID',
  LOGIN_ID VARCHAR(20) NOT NULL  COMMENT 'ログインID',
  USER_PASSWORD VARCHAR(44) NOT NULL  COMMENT 'パスワード',
  USER_ID_LOCKED BOOL NOT NULL  COMMENT 'ユーザIDロック',
  PASSWORD_EXPIRATION_DATE DATE NOT NULL  COMMENT 'パスワード有効期限',
  FAILED_COUNT SMALLINT NOT NULL  COMMENT '認証失敗回数',
  EFFECTIVE_DATE_FROM DATE NULL DEFAULT NULL  COMMENT '有効期限(FROM)',
  EFFECTIVE_DATE_TO DATE NULL DEFAULT NULL  COMMENT '有効期限(TO)',
  LAST_LOGIN_DATE_TIME TIMESTAMP(6) NULL DEFAULT NULL  COMMENT '最終ログイン日時',
  VERSION BIGINT NOT NULL  DEFAULT 1  COMMENT 'バージョン番号'
)
COMMENT='システムアカウント'