CREATE TABLE PASSWORD_HISTORY (
  PASSWORD_HISTORY_ID BIGINT NOT NULL  COMMENT 'パスワード履歴',
  USER_ID INT NULL DEFAULT NULL  COMMENT 'ユーザID',
  USER_PASSWORD VARCHAR(44) NOT NULL  COMMENT 'パスワード'
)
COMMENT='パスワード変更履歴'