CREATE TABLE CLIENT (
  CLIENT_ID SERIAL NOT NULL,
  CLIENT_NAME VARCHAR(128) NOT NULL,
  INDUSTRY_CODE CHAR(2) NOT NULL
);
COMMENT ON table CLIENT is '顧客';
COMMENT ON column CLIENT.CLIENT_ID is '顧客ID';
COMMENT ON column CLIENT.CLIENT_NAME is '顧客名';
COMMENT ON column CLIENT.INDUSTRY_CODE is '業種コード';
