services:
  web:
    build: .
    tty: true
    ports:
      - target: 8080
        published: 8080
  prom:
    restart: always
    image: prom/prometheus:v3.0.0-beta.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=otlp-write-receiver'
      - '--enable-feature=native-histograms'
    ports:
      - '9090:9090'
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
        mode: 440

configs:
  prometheus:
    file: ./prometheus.yml
