CREATE TABLE `PASSWORD_HISTORY` (
  `PASSWORD_HISTORY_ID` bigint NOT NULL COMMENT 'パスワード履歴',
  `USER_ID` int DEFAULT NULL COMMENT 'ユーザID',
  `USER_PASSWORD` varchar(44) NOT NULL COMMENT 'パスワード',
  PRIMARY KEY (`PASSWORD_HISTORY_ID`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_1` (`USER_ID`),
  CONSTRAINT `fk_1` FOREIGN KEY (`USER_ID`) REFERENCES `SYSTEM_ACCOUNT` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='パスワード変更履歴';