CREATE TABLE `USERS` (
  `USER_ID` int NOT NULL COMMENT 'ユーザID',
  `KANJI_NAME` varchar(128) NOT NULL COMMENT '漢字氏名',
  `KANA_NAME` varchar(128) NOT NULL COMMENT 'ふりがな',
  PRIMARY KEY SYS_C0058527(`USER_ID`) /*T![clustered_index] CLUSTERED */,
  CONSTRAINT `SYS_C0058527` FOREIGN KEY (`USER_ID`) REFERENCES `SYSTEM_ACCOUNT` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='ユーザ';