CREATE TABLE `CLIENT` (
  `CLIENT_ID` int NOT NULL COMMENT '顧客ID',
  `CLIENT_NAME` varchar(128) NOT NULL COMMENT '顧客名',
  `INDUSTRY_CODE` char(2) NOT NULL COMMENT '業種コード',
  PRIMARY KEY (`CLIENT_ID`) /*T![clustered_index] CLUSTERED */,
  KEY `fk_1` (`INDUSTRY_CODE`),
  CONSTRAINT `fk_1` FOREIGN KEY (`INDUSTRY_CODE`) REFERENCES `INDUSTRY` (`INDUSTRY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='顧客';