CREATE TABLE `SYSTEM_ACCOUNT` (
  `USER_ID` int NOT NULL COMMENT 'ユーザID',
  `LOGIN_ID` varchar(20) NOT NULL COMMENT 'ログインID',
  `USER_PASSWORD` varchar(44) NOT NULL COMMENT 'パスワード',
  `USER_ID_LOCKED` tinyint(1) NOT NULL COMMENT 'ユーザIDロック',
  `PASSWORD_EXPIRATION_DATE` date NOT NULL COMMENT 'パスワード有効期限',
  `FAILED_COUNT` smallint NOT NULL COMMENT '認証失敗回数',
  `EFFECTIVE_DATE_FROM` date DEFAULT NULL COMMENT '有効期限(FROM)',
  `EFFECTIVE_DATE_TO` date DEFAULT NULL COMMENT '有効期限(TO)',
  `LAST_LOGIN_DATE_TIME` timestamp(6) NULL DEFAULT NULL COMMENT '最終ログイン日時',
  `VERSION` bigint NOT NULL DEFAULT '1' COMMENT 'バージョン番号',
  PRIMARY KEY (`USER_ID`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `LOGIN_ID` (`LOGIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='システムアカウント';