CREATE TABLE `INDUSTRY` (
  `INDUSTRY_CODE` char(2) NOT NULL COMMENT '業種コード',
  `INDUSTRY_NAME` varchar(50) DEFAULT NULL COMMENT '業種名',
  PRIMARY KEY (`INDUSTRY_CODE`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='業種';